apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: aia-ip-controller
    qcloud-app: aia-ip-controller
  name: aia-ip-controller
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: aia-ip-controller
      qcloud-app: aia-ip-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: aia-ip-controller
        qcloud-app: aia-ip-controller
    spec:
      hostNetwork: true
      containers:
        - command:
            - /app/bin/aia-ip-controller
            - --aia-conf-path=/app/conf/values.yaml
            - -v=3
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: hkccr.ccs.tencentyun.com/tkeimages/aia-ip-controller:v0.10.0
          imagePullPolicy: Always
          name: aia-ip-controller
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
          securityContext:
            privileged: false
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: values-yaml
              mountPath: /app/conf/
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - hostnames:
            - cbs.api.qcloud.com
            - cvm.api.qcloud.com
            - lb.api.qcloud.com
            - snapshot.api.qcloud.com
            - monitor.api.qcloud.com
            - scaling.api.qcloud.com
            - ccs.api.qcloud.com
            - tag.api.qcloud.com
          ip: 169.254.0.28
        - hostnames:
            - vpc.tencentcloudapi.com
            - cbs.tencentcloudapi.com
            - cvm.tencentcloudapi.com
            - tag.tencentcloudapi.com
            - tke.internal.tencentcloudapi.com
            - clb.internal.tencentcloudapi.com
            - cvm.internal.tencentcloudapi.com
            - tag.internal.tencentcloudapi.com
          ip: 169.254.0.95
      volumes:
        - name: values-yaml
          configMap:
            name: aia-ip-controller
            items:
              - key: values.yaml
                path: values.yaml
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aia-ip-controller
      serviceAccountName: aia-ip-controller
      terminationGracePeriodSeconds: 30